buildscript {
    repositories { google(); mavenCentral() }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.flufflehook'
    compileSdk 34
    defaultConfig {
        applicationId 'com.flufflehook'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://api.xposed.info/' }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
